version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: ../../../../../../../../home/ec2-user/aws-codedeploy-scripts/application_stop_hook.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: ../../../../../../../../home/ec2-user/aws-codedeploy-scripts/application_stop_hook.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: ../../../../../../../../home/ec2-user/aws-codedeploy-scripts/application_stop_hook.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: ../../../../../../../../home/ec2-user/aws-codedeploy-scripts/application_stop_hook.sh
      timeout: 60
      runas: ec2-user
