version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: before_install_hook.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install_hook.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: application_start_hook.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: application_stop_hook.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: validate_service_hook.sh
      timeout: 60
      runas: ec2-user
